pipeline {
  agent any

  environment {
      IMAGE_NAME = 'ryanglug/jenkins-flask'
      IMAGE_TAG = 'latest'
      DOCKER_USERNAME = credentials('dockerhub-user')
      DOCKER_PASSWORD = credentials('dockerhub-pass')
  }

  stages {
    stage('Test') {
      agent {
        label 'python-agent'
      }
      steps {
        sh 'python3 -m venv venv'
        sh '. venv/bin/activate && cd app && pip install -r requirements.txt && pytest'
      }
    }
    stage('Build') {
      agent {
        label 'docker-agent'
      }
      steps {
         sh 'cd app && docker build -t $IMAGE_NAME:$IMAGE_TAG .'
         sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $IMAGE_NAME:$IMAGE_TAG'
      }
    }
  }
}